name: PlaxerHub
version: '${project.version}'
main: org.plaxerstudios.it.plaxerhub.PlaxerHub
api-version: 1.18
authors: [Plaxer's Studios developer]
softdepend:
  - ProtocolLib
commands:
  spawn:
  setSpawn:
    permission: plaxerhub.setSpawn
  crgui:
    permission: plaxerhub.block
  block:
    permission: plaxerhub.block
